import styled from 'styled-components'
import {colors} from '../../../constants/colors'

export const Container = styled.div`
    display:flex;
    justify-content:flex-start;
    position: relative;
    margin:0;
    padding:0;
    background-image: linear-gradient(to right,${colors.white}, ${colors.greenButtonHover},${colors.verdeagua});
    font-size:12px;
    span{
        font-weight:bold;
    }
    ul{
        margin:0;
        padding-left:1em;
        list-style:none;
        height:100%;
        width:40%;
        display:flex;
        flex-direction:column;
        justify-content:space-around;
        li{
            padding:0;
            margin:0;
            span{
                width:20%;
            }
            input{
                width:80%;

            }
            display:flex;
        }
    }
    div{
        margin-top:1em;
        padding-left:.5em;
        width:30%;
        p{
        width:100%;
        display:flex;
        justify-content:space-between;
            span{
            width:30%;
            }
            input{
            width:70%;
            }
        }
        
    }
    #wrapperButtons{
        display:flex;
        flex-direction:row;
       
        width:100%;
        justify-content:space-evenly;
        #prontuarios{
            display:flex;
           flex-direction:column;
           justify-content:center;
           align-items:center;
            width:80px;
            height:80px;
            cursor:pointer;
            img{
                width:100%;
                object-fit:contain;
            }
            label{
                font-size:14px;
                font-weight:bold;
                color:white;
            }
        }
    
        #save{
           display:flex;
           flex-direction:column;
           justify-content:center;
           align-items:center;
            width:80px;
            height:80px;
            cursor:pointer;
            img{
                width:100%;
                object-fit:contain;
            }
            label{
                font-size:14px;
                font-weight:bold;
                color:white;
                
            }
        }
    }
    #showVia{
        z-index:100;
        position:fixed;
        top:0;
        left:0;
        right:0;
        bottom:0;
        width:100%;
        height:105%;
        margin-top:-10px;
        background-color:rgba(0,0,0,.5);
        display:flex;
        justify-content:center;
        align-items:center;
        #content{
            background-image: linear-gradient(to right,${colors.white}, ${colors.greenButtonHover},${colors.verdeagua});
            height:50vh;
            width:40vw;
            display:flex;
            flex-direction:column;
            justify-content:space-evenly;
            align-items:center;
            input{
                width:80%;
                height:3em;
            }
            button{
                border:none;
                width:50%;
                height:3em;
                font-size:2em;
                font-weight:bold;
                &:hover{
                    background-color:${colors.verdeagua};
                    color:white;
                }
            }
        }
    }
    #showOFAS{
        z-index:100;
        position:fixed;
        top:0;
        left:0;
        right:0;
        bottom:0;
        width:100%;
        height:105%;
        margin-top:-10px;
        background-color:rgba(0,0,0,.5);
        display:flex;
        justify-content:center;
        align-items:center;
        #content{
            background-image: linear-gradient(to right,${colors.white}, ${colors.greenButtonHover},${colors.verdeagua});
            height:50vh;
            width:40vw;
            display:flex;
            flex-direction:column;
            justify-content:space-evenly;
            align-items:center;
            input{
                width:80%;
                height:3em;
            }
            button{
                border:none;
                width:50%;
                height:3em;
                font-size:2em;
                font-weight:bold;
                &:hover{
                    background-color:${colors.verdeagua};
                    color:white;
                }
            }
        }
    }
`