import React, { useState, useEffect } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
} from "recharts";
import { Container, ChartContainer, NavBar } from "./style.js";
import { TextField, Button } from "@material-ui/core";

function Home() {
  const [data, setData] = useState();
  const [count, setCount] = useState(0);
  const [totalSetor, setTotalSetor] = useState();
  const [totalSemana, setTotalSemana] = useState([0, 0, 0, 0]);
  const [pendenciasSetor, setPendenciasSetor] = useState();
  const [pendenciasSemana, setPendenciasSemana] = useState([0, 0, 0, 0]);
  const [dataTable, setDataTable] = useState(
    sessionStorage.getItem("table")
      ? JSON.parse(sessionStorage.getItem("table"))
      : [
          {
            data: [
              {
                utineo: 17,
                utiped: 5,
                uti1: 5,
                uti2: 7,
                uti3: 13,
                uti4: 2,
                uti5: 0,
                uti6: 20,
                uti7: 0,
                uti8: 7,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 8,
                utiped: 3,
                uti1: 7,
                uti2: 3,
                uti3: 3,
                uti4: 2,
                uti5: 0,
                uti6: 17,
                uti7: 0,
                uti8: 7,
                uti9: 0,
                uti10: 2,
                uti11: 3,
                uti12: 0,
              },
              {
                utineo: 7,
                utiped: 9,
                uti1: 1,
                uti2: 1,
                uti3: 2,
                uti4: 5,
                uti5: 1,
                uti6: 9,
                uti7: 1,
                uti8: 2,
                uti9: 0,
                uti10: 2,
                uti11: 2,
                uti12: 0,
              },
              {
                utineo: 17,
                utiped: 1,
                uti1: 5,
                uti2: 0,
                uti3: 6,
                uti4: 1,
                uti5: 0,
                uti6: 18,
                uti7: 3,
                uti8: 6,
                uti9: 0,
                uti10: 11,
                uti11: 5, //posto2
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [76, 52, 40, 68],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [2, 6, 5, 3],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
        ]
  );
  const [meses, setMeses] = useState([
    "Novembro 2019",
    "Dezembro 2019",
    "Janeiro 2020",
    "Fevereiro 2020",
    "Março 2020",
    "Abril 2020",
    "Maio 2020",
    "Junho 2020",
    "Julho 2020",
    "Agosto 2020",
    "Setembro 2020",
    "Outubro 2020",
  ]);

  useEffect(() => {
    setData(dataTable[count].data);
    setTotalSetor(dataTable[count].totalSetor);
    setTotalSemana(dataTable[count].totalSemana);
    setPendenciasSetor(dataTable[count].pendenciasSetor);
    setPendenciasSemana(dataTable[count].pendenciasSemana);
  }, [count]);

  const chartData = [
    {
      name: "Semana 1",
      atendimentos: totalSemana[0],
      pendencias: pendenciasSemana[0],
      amt: 2400,
    },
    {
      name: "Semana 2",
      atendimentos: totalSemana[1],
      pendencias: pendenciasSemana[1],
      amt: 2400,
    },
    {
      name: "Semana 3",
      atendimentos: totalSemana[2],
      pendencias: pendenciasSemana[2],
      amt: 2400,
    },
    {
      name: "Semana 4",
      atendimentos: totalSemana[3],
      pendencias: pendenciasSemana[3],
      amt: 2400,
    },
  ];

  return (
    <Container>
      <NavBar>
        <button
          id="anterior"
          onClick={() => {
            if (count > 0) {
              setCount(count - 1);
            }
          }}
        ></button>
        <span>{meses[count]}</span>
        <button
          id="posterior"
          onClick={() => {
            if (count < 11) {
              setCount(count + 1);
            }
          }}
        ></button>
      </NavBar>
      <ChartContainer>
        <BarChart responsive={true} width={800} height={400} data={chartData}>
          <CartesianGrid />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend />
          <Bar type="monotone" dataKey="atendimentos" fill="#8884d8" />
          <Bar
            type="monotone"
            stackId="a"
            dataKey="pendencias"
            fill="#82ca9d"
          />
        </BarChart>
      </ChartContainer>
    </Container>
  );
}

export default Home;
