import React, { useState, useEffect } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  PieChart,
  Pie,
  Sector,
  Cell,
} from "recharts";
import { Container, ChartContainer, NavBar } from "./style.js";
import { TextField, Button } from "@material-ui/core";
import { colors } from "../../constants/colors.js";

function Home() {
  const [state, setState] = useState({ activeIndex: 0 });
  const [data, setData] = useState();
  const [count, setCount] = useState(0);
  const [totalSetor, setTotalSetor] = useState();
  const [totalSemana, setTotalSemana] = useState([0, 0, 0, 0]);
  const [pendenciasSetor, setPendenciasSetor] = useState();
  const [pendenciasSemana, setPendenciasSemana] = useState([0, 0, 0, 0]);
  const [dataTable, setDataTable] = useState(
    sessionStorage.getItem("table")
      ? JSON.parse(sessionStorage.getItem("table"))
      : [
          {
            data: [
              {
                utineo: 17,
                utiped: 5,
                uti1: 5,
                uti2: 7,
                uti3: 13,
                uti4: 2,
                uti5: 0,
                uti6: 20,
                uti7: 0,
                uti8: 7,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 8,
                utiped: 3,
                uti1: 7,
                uti2: 3,
                uti3: 3,
                uti4: 2,
                uti5: 0,
                uti6: 17,
                uti7: 0,
                uti8: 7,
                uti9: 0,
                uti10: 2,
                uti11: 3,
                uti12: 0,
              },
              {
                utineo: 7,
                utiped: 9,
                uti1: 1,
                uti2: 1,
                uti3: 2,
                uti4: 5,
                uti5: 1,
                uti6: 9,
                uti7: 1,
                uti8: 2,
                uti9: 0,
                uti10: 2,
                uti11: 2,
                uti12: 0,
              },
              {
                utineo: 17,
                utiped: 1,
                uti1: 5,
                uti2: 0,
                uti3: 6,
                uti4: 1,
                uti5: 0,
                uti6: 18,
                uti7: 3,
                uti8: 6,
                uti9: 0,
                uti10: 11,
                uti11: 5, //posto2
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [76, 52, 40, 68],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [2, 6, 5, 3],
          },
          {
            data: [
              {
                utineo: 15,
                utiped: 1,
                uti1: 8,
                uti2: 0,
                uti3: 3,
                uti4: 2,
                uti5: 0,
                uti6: 17,
                uti7: 0,
                uti8: 12,
                uti9: 0,
                uti10: 8,
                uti11: 2,
                uti12: 0,
              },
              {
                utineo: 19,
                utiped: 0,
                uti1: 7,
                uti2: 1,
                uti3: 6,
                uti4: 3,
                uti5: 0,
                uti6: 19,
                uti7: 0,
                uti8: 11,
                uti9: 0,
                uti10: 4,
                uti11: 2,
                uti12: 0,
              },
              {
                utineo: 19,
                utiped: 4,
                uti1: 3,
                uti2: 0,
                uti3: 6,
                uti4: 2,
                uti5: 1,
                uti6: 19,
                uti7: 0,
                uti8: 4,
                uti9: 0,
                uti10: 1,
                uti11: 2,
                uti12: 0,
              },
              {
                utineo: 8,
                utiped: 2,
                uti1: 4,
                uti2: 3,
                uti3: 9,
                uti4: 13,
                uti5: 1,
                uti6: 28,
                uti7: 12,
                uti8: 3,
                uti9: 0,
                uti10: 8,
                uti11: 4,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [68, 72, 61, 95],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [11, 1, 11, 2],
          },
          {
            data: [
              {
                utineo: 7,
                utiped: 1,
                uti1: 5,
                uti2: 0,
                uti3: 8,
                uti4: 10,
                uti5: 2,
                uti6: 2,
                uti7: 0,
                uti8: 3,
                uti9: 0,
                uti10: 4,
                uti11: 4,
                uti12: 0,
              },
              {
                utineo: 15,
                utiped: 4,
                uti1: 6,
                uti2: 0,
                uti3: 6,
                uti4: 20,
                uti5: 7,
                uti6: 3,
                uti7: 0,
                uti8: 5,
                uti9: 0,
                uti10: 11,
                uti11: 6,
                uti12: 0,
              },
              {
                utineo: 26,
                utiped: 3,
                uti1: 2,
                uti2: 2,
                uti3: 8,
                uti4: 16,
                uti5: 2,
                uti6: 7,
                uti7: 0,
                uti8: 3,
                uti9: 0,
                uti10: 6,
                uti11: 4,
                uti12: 0,
              },
              {
                utineo: 14,
                utiped: 8,
                uti1: 4,
                uti2: 5,
                uti3: 10,
                uti4: 5,
                uti5: 6,
                uti6: 10,
                uti7: 3,
                uti8: 7,
                uti9: 0,
                uti10: 9,
                uti11: 8,
                uti12: 5,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [46, 83, 79, 94],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [4, 3, 6, 7],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
          {
            data: [
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
              {
                utineo: 0,
                utiped: 0,
                uti1: 0,
                uti2: 0,
                uti3: 0,
                uti4: 0,
                uti5: 0,
                uti6: 0,
                uti7: 0,
                uti8: 0,
                uti9: 0,
                uti10: 0,
                uti11: 0,
                uti12: 0,
              },
            ],
            totalSetor: {
              utineo: 0,
              utiped: 0,
              uti1: 0,
              uti2: 0,
              uti3: 0,
              uti4: 0,
              uti5: 0,
              uti6: 0,
              uti7: 0,
              uti8: 0,
              uti9: 0,
              uti10: 0,
              uti11: 0,
              uti12: 0,
            },
            totalSemana: [0, 0, 0, 0],
            pendenciasSetor: {
              utineo: [0, 0, 0, 0],
              utiped: [0, 0, 0, 0],
              uti1: [0, 0, 0, 0],
              uti2: [0, 0, 0, 0],
              uti3: [0, 0, 0, 0],
              uti4: [0, 0, 0, 0],
              uti5: [0, 0, 0, 0],
              uti6: [0, 0, 0, 0],
              uti7: [0, 0, 0, 0],
              uti8: [0, 0, 0, 0],
              uti9: [0, 0, 0, 0],
              uti10: [0, 0, 0, 0],
              uti11: [0, 0, 0, 0],
              uti12: [0, 0, 0, 0],
            },
            pendenciasSemana: [0, 0, 0, 0],
          },
        ]
  );
  const [meses, setMeses] = useState([
    "Novembro 2019",
    "Dezembro 2019",
    "Janeiro 2020",
    "Fevereiro 2020",
    "Março 2020",
    "Abril 2020",
    "Maio 2020",
    "Junho 2020",
    "Julho 2020",
    "Agosto 2020",
    "Setembro 2020",
    "Outubro 2020",
  ]);

  useEffect(() => {
    setData(dataTable[count].data);
    setTotalSetor(dataTable[count].totalSetor);
    setTotalSemana(dataTable[count].totalSemana);
    setPendenciasSetor(dataTable[count].pendenciasSetor);
    setPendenciasSemana(dataTable[count].pendenciasSemana);
  }, [count]);

  const chartData = [
    {
      name: "Semana 1",
      atendimentos: totalSemana[0],
      pendencias: pendenciasSemana[0],
      amt: 2400,
    },
    {
      name: "Semana 2",
      atendimentos: totalSemana[1],
      pendencias: pendenciasSemana[1],
      amt: 2400,
    },
    {
      name: "Semana 3",
      atendimentos: totalSemana[2],
      pendencias: pendenciasSemana[2],
      amt: 2400,
    },
    {
      name: "Semana 4",
      atendimentos: totalSemana[3],
      pendencias: pendenciasSemana[3],
      amt: 2400,
    },
  ];

  const dataPie = [
    {
      name: "Atendimentos",
      value: Number(
        totalSemana[0] + totalSemana[1] + totalSemana[2] + totalSemana[3]
      ),
      fill: colors.verdeagua,
    },
    {
      name: "Pendências",
      value: Number(
        pendenciasSemana[0] +
          pendenciasSemana[1] +
          pendenciasSemana[2] +
          pendenciasSemana[3]
      ),
      fill: colors.pink,
    },
  ];

  const renderActiveShape = (props) => {
    const RADIAN = Math.PI / 180;
    const {
      cx,
      cy,
      midAngle,
      innerRadius,
      outerRadius,
      startAngle,
      endAngle,
      fill,
      payload,
      percent,
      value,
    } = props;
    const sin = Math.sin(-RADIAN * midAngle);
    const cos = Math.cos(-RADIAN * midAngle);
    const sx = cx + (outerRadius + 10) * cos;
    const sy = cy + (outerRadius + 10) * sin;
    const mx = cx + (outerRadius + 30) * cos;
    const my = cy + (outerRadius + 30) * sin;
    const ex = mx + (cos >= 0 ? 1 : -1) * 22;
    const ey = my;
    const textAnchor = cos >= 0 ? "start" : "end";

    return (
      <g>
        <text x={cx} y={cy} dy={8} textAnchor="middle" fill={fill}>
          {payload.name}
        </text>
        <Sector
          cx={cx}
          cy={cy}
          innerRadius={innerRadius}
          outerRadius={outerRadius}
          startAngle={startAngle}
          endAngle={endAngle}
          fill={fill}
        />
        <Sector
          cx={cx}
          cy={cy}
          startAngle={startAngle}
          endAngle={endAngle}
          innerRadius={outerRadius + 6}
          outerRadius={outerRadius + 10}
          fill={fill}
        />
        <path
          d={`M${sx},${sy}L${mx},${my}L${ex},${ey}`}
          stroke={fill}
          fill="none"
        />
        <circle cx={ex} cy={ey} r={2} fill={fill} stroke="none" />
        <text
          x={ex + (cos >= 0 ? 1 : -1) * 12}
          y={ey}
          textAnchor={textAnchor}
          fill="#333"
        >{`Total ${value}`}</text>
        <text
          x={ex + (cos >= 0 ? 1 : -1) * 12}
          y={ey}
          dy={18}
          textAnchor={textAnchor}
          fill="#999"
        >
          {`(${(percent * 100).toFixed(2)}%)`}
        </text>
      </g>
    );
  };

  const onPieEnter = (data, index) => {
    setState({
      activeIndex: index,
    });
  };
  return (
    <Container>
      <NavBar>
        <button
          id="anterior"
          onClick={() => {
            if (count > 0) {
              setCount(count - 1);
            }
          }}
        ></button>
        <span>{meses[count]}</span>
        <button
          id="posterior"
          onClick={() => {
            if (count < 11) {
              setCount(count + 1);
            }
          }}
        ></button>
      </NavBar>
      <ChartContainer>
        <BarChart width={600} height={400} data={chartData}>
          <CartesianGrid />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Bar type="monotone" dataKey="atendimentos" fill={colors.verdeagua} />
          <Bar
            type="monotone"
            stackId="a"
            dataKey="pendencias"
            fill={colors.pink}
          />
          <Legend />
        </BarChart>
        <PieChart responsive={true} width={600} height={400}>
          <Pie
            activeIndex={state.activeIndex}
            activeShape={renderActiveShape}
            data={dataPie}
            cx={250}
            cy={200}
            innerRadius={60}
            outerRadius={80}
            dataKey="value"
            onMouseEnter={onPieEnter}
          />
        </PieChart>
      </ChartContainer>
    </Container>
  );
}

export default Home;
